# API keys "secure" but not really
services:
  - docker

before_install: npm install -g npm@latest
install: npm ci

after_success:
  - sha256sum build/* > build/SHA256SUMS
  - cat build/SHA256SUMS

script:
  - >-
    version=$(grep '"version":' src/drivers/webextension/manifest.json | sed 's/^.*"version": "\(.*\)".*$/\1/') ;
    ./run build $version ;
    docker build -t wappalyzer/cli:latest -t wappalyzer/cli:$version src/drivers/npm

env:
  - secure: xc5vP+LjpNnZgMIfXUUeP3EBGhhNoDV5vTfophBliaWZrBX8POpLOFQGZ/Fcd0i+UBmSckLYW30BLSwHwjYLAZJGM12AfeiKbI1eub5tNfsosI2FZ3lNeb2nlpoIjzpsyS5fknJL0zQfkadUgxbrwDRDuaN+P6oOup3XMgHR9hkjb/QwVW2ozxU+OP4iRvcNECLP+XqnsOyq0YFshZzRMOd6fVYnJZuP6NTj24hCfymcmZJlS8Q5dSHISg68Lckaa/z3APxrMW+5/PORsHZ/U8yugNQr6Ty5J3YoaEuUoaMaUkGpaiuP26/lndynlRhNVlw8zQKfb7A09oom/UjnhyLE+9NuhKpo7f3l56OP/ubIvJzkrGt0hqwKnW2+EixURLxAOL7shtc/9gl8q2cPwEJg50siIRGJXkUEear/oqYr/EqEk1/6kq3dOfaDM0kRYAeHi8Kuf4+tyTbKQDULT3xYMi3ZxAYTd8gEMGsWca+PT/+IfFB4sHADmFmh6Y9VhI89Zrsrqa7C2BlS/ytuiAJHgrleKxyYKEFy78yG5Tb/AGi2UmGFMk8ShKRNrK8VJmrqixWttvyUr81iBI5uEP9copsXDnR5aZaFZF5vBi7PK85Ngwj6uREM+rjQadaPR49KQqUXFj0s3OXbwDXgMFIXAguqsji/nm4IuEeA8zA=

deploy:
- provider: releases
  api_key:
    secure: mco1ycbfGXZEiBywOmM5A50Y1QPFawj4i0gdB9JDkXDvY7N2kPZyCdAeOQOMEJuetGT3HvJuTG0Ll47sithZfPqq6wx/4EeP8YQYYFIyoOlsIGi5MDR1kS5ZOqKDWGe5+x+/rUZbmuMHvgHWNSjPG8mBrp5xWmON6ETkLWfVB0c=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    repo: AliasIO/wappalyzer
    tags: true
- provider: script
  script:
    - docker login -u wappalyzer -p "$DOCKER_PASSWORD" && docker push wappalyzer/cli
  on:
    repo: AliasIO/wappalyzer
    tags: true

notifications:
  slack: wappalyzer:ppXlJRMBDxrKYS9vgVxT7FuH
